### ISSUE TITLE
Proposed management API and general tidyup

### ISSUE THREAD

**Issue by andydotxyz** [fynelabs/selfupdate#1]
Start of discussion for a new API for the self-update package.

It focusses more on pluggable components than the low level `io.Reader` usage, this allows us to provide S3, HTTP etc wrappers for common usage.

```go
package update

import (
	"errors"
	"io"
	"time"
)

// ErrNotSupported is returned by `Manage` when it is not possible to manage the current application.
var ErrNotSupported = errors.New("operating system not supported")

type Source interface {
	Get() (uint64, io.Reader, error)
}

type Schedule struct {
	FetchOnStart bool
	Interval     time.Duration
}

type Config struct {
	Source   Source
	Schedule Schedule

	AcceptCallback func(string) bool // if present will ask for user acceptance, it can present the message passed
	ProgressCallback func(float32, error) // if present will call back with 0.0 at the start, rising through to 1.0 at the end if the progress is known. A negative start number will be sent if size is unknown, any error will pass as is and the process is considered done
}

type Updater struct {}

func (u *Updater) CheckNow() error {
	return nil
}

// Manage sets up an Updater and runs it to manage the current executable.
func Manage(Config) (*Updater, error) {
	return nil, ErrNotSupported
}

// ManualUpdate applies a specific update manually instead of managing the update of this app automatically.
func ManualUpdate(Source) error {
	return ErrNotSupported
}
```

**Comment by andydotxyz** [comment]
In addition it would be possible to handle the user interface element of confirming update using a simple dialog box as shown below. Where that is would depend on where we are happy having a `fyne` dependency...

```go
func FyneConfirm(win fyne.Window, timeout time.Duration) (func() bool) {
	return func() bool {
		// TODO show confirm dialog and wait for answer...
		// Or hide after `timeout` if specified
		return true
	}
}

Config.AcceptCallback = selfupdate.FyneConfirm(win, time.Second*30)
```

**Comment by Bluebugs** [comment]
I am just wondering if AcceptCallback is enough. I would think AcceptCallback is only for doing the download and applying the change on the binary, but it won't restart automatically at the end. Or does it always do the download and AcceptCallback is just before restart? Which kind of make me think we should also have a RestartCallback.

I would also add a ProgressCallback for the download, just to be able to have some progress bar somewhere showing it.

What do you think?

I am expecting we will provide NewHTTPSource and a NewS3Source, do you have some idea for those API?

**Comment by Bluebugs** [comment]
Just working on the metadata download trigger and it would be nice to use just `if-modified-since` as it is available in both S3 and CDN HTTP. So would consider the following change:
```
type Source interface {
	Get(ifModifiedSince *time.Time) (io.Reader, error)
}
```

**Comment by Bluebugs** [comment]
I am realizing, that we might want more parameters to Get or different Get. One for the Metadata and one to Get a specific architecture (maybe with a "enum" for i386, amd64, arm and arm64)(Also maybe specifying a different OS than Windows, but not sure of that).

The other possibility would be to pass the OS/Architecture to the NewHTTPSource/NewS3Source constructor, which would also make sense to me.

So maybe:
```func NewHTTPSource(client *http.Client, base *url.URL, os string, architecture string) Source```
```func NewS3Source(aws *session.Session, base string, os string, architecture string) Source```

and
```
type Source interface {
	GetMetadata(ifModifiedSince time.Time) (io.Reader, error)
        GetExecutable() (io.Reader, error)
}
```

**Comment by andydotxyz** [comment]
> One for the Metadata and one to Get a specific architecture (maybe with a "enum" for i386, amd64, arm and arm64)(Also maybe specifying a different OS than Windows, but not sure of that).

I don't think we need to pass this in - we are in "self update" land so the OS and ARCH are both available in the `runtime` package

> Just working on the metadata download trigger and it would be nice to use just if-modified-since as it is available in both S3 and CDN HTTP. So would consider the following change:

I agree that using if-modified-since makes sense for these two, but it might not for all sources. So it should be in the implementation, not the interface.

**Comment by andydotxyz** [comment]
Instead of MTime how about the `Source` interface has a check, with a new version type:

```go
type Version struct {
	Number string // if the app knows its version and supports checking metadata
	Build int // if the app has a build number this could be compared
	Date time.Time // last update, could be mtime
}

type Config struct {
...
	Current *Version
}

type Source interface {
	Get(*Version) (io.Reader, error)
	GetSignature() (string, error)
	LatestVersion() (*Version, error)
}
```

**Comment by andydotxyz** [comment]
Merged :)
