### ISSUE TITLE
Struggle updating

### ISSUE THREAD

**Issue by joe-cranney** [fynelabs/selfupdate#27]
Hello, examples are a bit unclear. I am trying to implement auto update into my Go binary however I run into an error:

```
Upgrade error: ed25519 signature must be 64 bytes long and was -1
```

```go
publicKey := ed25519.PublicKey{REDACTED}

		httpSource := selfupdate.NewHTTPSource(nil, "https://localhost/myurl")
		config := &selfupdate.Config{
			Source:   httpSource,
			Schedule: selfupdate.Schedule{FetchOnStart: true, Interval: time.Minute * time.Duration(5)},
			PublicKey: publicKey,

			RestartConfirmCallback: func() bool {
				if constants.DEBUG {
					return true
				}
				answer, _ := dlgs.Question("app", "A new update was installed. A restart is required to apply the changes. Ok?", false)
				return answer
			},
			UpgradeConfirmCallback: func(s string) bool {
				if constants.DEBUG {
					return true
				}
				answer, _ := dlgs.Question("app", "A new update is available, would you like to install?", false)
				return answer
			},
			ExitCallback: func(err error) {
				os.Exit(1)
			},
		}

		_, err := selfupdate.Manage(config)
		if err != nil {
            log.Println("Error while setting up update manager: ", err)
			return
		}
```

Note, I am manually generating the binary for my app. I then use [selfupdatectl](https://github.com/fynelabs/selfupdate/tree/main/cmd/selfupdatectl) to sign the binary using generated private key. I then take the EXE and upload to my URL. 

My code is practically 1:1 with the examples. What am I missing? Am I suppose to do something with the generated .ed25519 file?? If so, what?

**Comment by joe-cranney** [comment]
Figured it out. The `.ed25519` must also be uploaded to S3. I don't believe this was stated anywhere in the documentation.

**Comment by Bluebugs** [comment]
Thanks for the feedback, I will update the documentation to describe what need to be stored on S3. Did you try using `selfupdatectl` to do your upload? This should make sure that the `.ed25519` file is properly uploaded too.

**Comment by joe-cranney** [comment]
Ideally I want to use `selfupdatectl`, but the documentation was also a bit lacking to where I don't understand how to upload. Key generation and signing is clear, but uploading is unclear. If it's possible to add more examples on that, it would be helpful. Thank you.

**Comment by Bluebugs** [comment]
@jj0e I have created #28 to take care of it.
